service: kkodac

plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stage: dev
  timeout: 30
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  main: ${file(env.yml):dev}

package:
  individually: true

custom:
  serverless-offline:
    httpPort: 3049
    lambdaPort: 3002
  apigwBinary:
    types: #list of mime-types
      - '*/*'
