service: kkodac

plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-apigw-binary
  # - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stage: dev
  timeout: 30
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  main: ${file(env.yml):dev}

package:
  individually: true
  # excludeDevDependencies: false
  # patterns:
  #   - '!node_modules/**'
  #   - '../config'

custom:
  serverless-offline:
    httpPort: 3049
    lambdaPort: 3002
  apigwBinary:
    types: #list of mime-types
      - '*/*'

  # optimize:
  #   external:
  #     [
  #       'bcrypt',
  #       '@mapbox/node-pre-gyp',
  #       'nopt',
  #       'npmlog',
  #       'inherits',
  #       'util-deprecate',
  #       'delegates',
  #       'console-control-strings',
  #     ]
  #   includePaths: ['node_modules/bcrypt', 'node_modules/@mapbox']
